MONGO_HOST = 'localhost'
MONGO_PORT = 27017

DB_NAME = 'cleanteam'

CO_ORDS_DB = DB_NAME
CO_ORDS_COLL = 'co_ords'

LOCS_DB = DB_NAME
LOCS_COLL = 'locs'

CLUSTERS_DB = DB_NAME
CLUSTERS_COLL = 'clusters'

INITIAL_ROUTE_DB = DB_NAME
INITIAL_ROUTE_COLL = 'inital_route'

FINAL_ROUTE_DB = DB_NAME
FINAL_ROUTE_COLL = 'final_route'
